version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: banking-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bankingDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: